### ISSUE TITLE
project real imagen

### ISSUE THREAD

**Issue by loboere** [SizheAn/PanoHead#11]
can you tell me how to project real images and then use it to generate 3d head.

try !python projector.py --target /content/vv --outdir=out --network /content/PanoHead/models/easy-khair-180-gpc0.8-trans10-025000.pkl

but it gives the following error
```
/content/PanoHead
Loading networks from "/content/PanoHead/models/easy-khair-180-gpc0.8-trans10-025000.pkl"...
projecting: [0] /content/vv/34r43.png
camera matrix: torch.Size([1, 0])
Computing W midpoint and stddev using 10000 samples...
Setting up PyTorch plugin "bias_act_plugin"... Done.
Traceback (most recent call last):
  File "/content/PanoHead/projector.py", line 348, in <module>
    run_projection() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/content/PanoHead/projector.py", line 293, in run_projection
    projected_w_steps = project(
  File "/content/PanoHead/projector.py", line 109, in project
    synth_images = G.synthesis(ws, c=c, noise_mode='const')['image']
  File "<string>", line 87, in synthesis
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/PanoHead/training/volumetric_rendering/ray_sampler.py", line 47, in forward
    x_cam = uv[:, :, 0].view(N, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by SizheAn** [comment]
Looks like you didn't enter corresponding camera pose in the dataset.json?
