### ISSUE TITLE
"bias_act_plugin"...Failed!

### ISSUE THREAD

**Issue by MedTechWiz** [SizheAn/PanoHead#45]
Hello :)

I am struggling quite some time by now with the panohead configuration. I installed all the environment requirements for Panohead and checked up for the Stylegan3 requirements as well.

**Here some information about the current env:**
- Working on Linux
- Python 3.8.18
- torch 2.1.1
- cudatoolkit 11.8.0
- ninja 1.11.1
- GCC 11.4.0

**nvidia-smi output:**
![nvidia_smi](https://github.com/SizheAn/PanoHead/assets/153804707/a8e3a5cf-2699-45f1-ba83-e6f32357f6b8)

**nvcc --version output:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

**I'm trying to execute the following statement:**
python gen_videos.py --network models/easy-khair-180-gpc0.8-trans10-025000.pkl --seeds 0-3 --grid 2x2 --output=out --cfg Head --trunc 0.7

**Here the error message I am dealing with when executing:**
Loading networks from "models/easy-khair-180-gpc0.8-trans10-025000.pkl"...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
Traceback (most recent call last):
  File "/home/research-server/anaconda3/envs/panohead/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/research-server/anaconda3/envs/panohead/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gen_videos.py", line 365, in <module> etc.

I'm still not sure what is causing the error. Does anybody have some ideas?

**Comment by malteprinzler** [comment]
changing the environment.yml as below and reinstalling the environment solved the issue for me.
```
name: panohead
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2024.2.2=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - cryptography=41.0.7=py312hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py312h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.26.3=py312hc5e2394_0
  - numpy-base=1.26.3=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pillow=10.2.0=py312h5eee18b_0
  - pip=23.3.1=py312h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.1=h996f2a0_0
  - pytorch=2.2.0=py3.12_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py312h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py312h06a4308_0
  - scipy=1.11.4=py312hc5e2394_0
  - setuptools=68.2.2=py312h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.0=py312_cu121
  - torchvision=0.17.0=py312_cu121
  - tqdm=4.65.0=py312he106c6f_0
  - typing_extensions=4.9.0=py312h06a4308_1
  - tzdata=2023d=h04d1e81_0
  - urllib3=1.26.18=py312h06a4308_0
  - wheel=0.41.2=py312h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - mrcfile==1.5.0
```
